version: '3.2'

services:

  # Ghost server    
  ghost:
    image: allandequeiroz/ghost-the-shell
    ports:
      - mode: host
        target: 2368
        published: 2368
    volumes:
      - /lab/data/blog:/var/www/ghost/content/data/
