version: '2'

services:

  # Ghost server    
  ghost:
    image: allandequeiroz/ghost-the-shell
    restart: always  
    ports:
      - "80:2368"
    volumes:
      - $HOME/data/blog:/var/www/ghost/content/data/
      - $PWD/conf/config.production.json:/var/www/ghost/core/server/config/env/config.production.json
