version: '2'

services:

  # Ghost server    
  ghost:
    image: allandequeiroz/ghost-the-shell
    restart: always  
    ports:
      - "3000-80"
    volumes:
      - $HOME/data/blog:/var/www/ghost/content/data/
