version: '2'

services:

  # NGinx as a Ghost proxy    
  nginx:
    image: allandequeiroz/nginx:ghost-amd64
    restart: always  
    ports:
      - "443:443"   
  
  # Ghost server    
  ghost:
    image: allandequeiroz/ghost-the-shell
    restart: always 
    volumes:
      - $HOME/data/blog:/var/www/ghost/content/data/
      - $PWD/conf/config.production.json:/var/www/ghost/core/server/config/env/config.production.json
